name: Trigger SSH Script

on:
  push:
    branches:
      - main

jobs:
  run-ssh-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Execute SSH command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo "Lancement du Script"
          cd /home/kerboul/sites/CommusDCS/
          echo "Arrivée dans le dossier CommusDCS"
          git fetch
          echo "fetch done"
          git pull --force
          echo "pull done"
          npm run docs:build
          echo "Fin du Script"
