name: Trigger SSH Script

on:
  push:
    branches:
      - main

jobs:
  run-ssh-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.3.0'

      - name: Check npm version
        run: npm --version

      - name: Install dependencies
        run: npm install

      - name: Build documentation
        run: npm run docs:build

      - name: Install Vitepress
        run: npm add -D vitepress

      - name: Execute SSH command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Running SSH script..."
            /scripts/update_commus.sh

      - name: Copy dist folder using scp
        run: |
          scp -r ./docs/.vitepress/dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/kerboul/sites/CommusDCS/docs/.vitepress/dist/