name: Publish Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
        chmod 600 ~/ssh_key
        echo "SSH validé, prêt à se connecter au serveur web."

    - name: Launch site update
      run: |
        echo "Lancement du rendu du site..."
        ssh -i ~/ssh_key -o StrictHostKeyChecking=no ${{ secrets.SSH_HOST }} '/scripts/test.sh'
        echo "Site mis à jour."
