name: Trigger SSH Script

on:
  push:
    branches:
      - main

jobs:
  run-ssh-script:
    runs-on: ubuntu-latest
    steps:
    - name: Execute SSH command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo "Running SSH script..."
          /scripts/update_commus.sh

